"""add analysis summary to content

Revision ID: 294df3be34ee
Revises: b827a100ad96
Create Date: 2026-07-18 17:00:06.609240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294df3be34ee'
down_revision: Union[str, Sequence[str], None] = 'b827a100ad96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('analysis_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'analysis_summary')
    # ### end Alembic commands ###
