"""add analyzed_at to contents

Revision ID: 2a750f8800ff
Revises: 294df3be34ee
Create Date: 2026-07-21 10:42:23.850377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a750f8800ff'
down_revision: Union[str, Sequence[str], None] = '294df3be34ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('analyzed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'analyzed_at')
    # ### end Alembic commands ###
